FROM ubuntu:22.04
WORKDIR /ansible-k0s
# RUN apt update && apt install software-properties-common -y && add-apt-repository --yes --update ppa:ansible/ansible && apt install ansible python3-pip python3-venv -y
COPY . .
RUN apt update && apt install python3-pip openssh-client vim -y
# RUN python -m ensurepip --upgrade
RUN pip3 install -r requirements.txt
# RUN pip install proxmoxer && pip install requests

# FROM almalinux:9.2
# WORKDIR /ansible-k0s
# RUN dnf update -y && dnf install -y epel-release && dnf install ansible -y && dnf update -y && dnf install python3-pip -y
# COPY . .
# RUN python3 -m venv venv
# RUN source venv/bin/activate
# RUN pip install -r requirements.txt


# FROM python:latest
# WORKDIR /ansible-k0s
# COPY . .
# RUN pip3 install -r requirements.txt
# RUN apt update -y && apt install openssh-client -y