- name: k0s Playbook
  hosts: controller
  become: yes
  tasks:
    - name: Download Installer
      get_url:
      url: https://get.k0s.sh
      dest: "./k0s-installer.sh"
    - name: Copy Installer to nodes
      copy:
        src: "./k0s-installer.sh"
        dest: "/install-k0s/k0s-installer.sh"
        owner: "dirceu"
        group: "dirceu"
        mode: 0755
    - name: Install on single controller
      command: k0s install controller --single && k0s start && k0s status